name: car
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #theme plugins
  # lottie: ^1.4.3
  flutter_svg: ^1.1.5

  #logic plugins
  get: ^4.6.1
  device_apps: ^2.2.0
  
  eraser: ^2.0.0
  sqflite: ^2.0.2+1 
  # path_provider: ^2.0.11
  # connectivity_plus: ^2.3.0
  shared_preferences: ^2.0.13
  # flutter_cache_manager: ^3.3.0
  # flutter_local_notifications: ^9.6.0

  #not used plugins
  # permission_handler: ^9.2.0

  #used once plugings
  # flutter_native_splash: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholders/
    - assets/images/svgs/codes/
  #   - images/a_dot_ham.jpeg

 
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
